tasks:
  - name: terraform
    before: |
      source ./bin/terraform_cli_install.sh
      SOURCE ./bin/generate_tfrc_credentials.sh
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      source ./bin/aws_cli_install.sh
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform