tasks:
  - name: terraform
    before: |
      source ./bin/terraform_cli_install.sh
      source ./bin/generate_tfrc_credentials.sh
      source ./bin/set_terraform_alias.sh
      cp $PROJECT_ROOT/terraform.tfvars.example $PROJECT_ROOT/terraform.tfvars
  - name: aws-cli
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    before: |
      source ./bin/aws_cli_install.sh
      source ./bin/set_terraform_alias.sh
vscode:
  extensions:
    - amazonwebservices.aws-toolkit-vscode
    - hashicorp.terraform